{% set name = "scramp" %}
{% set version = "1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe055ebbebf4397b9cb323fcc4b299f219cd1b03fd673ca40c97db04ac7d107e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - versioningit
  run:
    - python >={{ python_min }}
    - asn1crypto >=1.5.1

test:
  imports:
    - scramp
  commands:
    - pip check
    - python -c 'import scramp; print(scramp.__version__)'
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tlocke/scramp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pure-Python implementation of the SCRAM authentication protocol
  description: |
    A Python implementation of the SCRAM authentication protocol defined by
    RFC 5802 and RFC 7677.

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - xylar

