{% set name = "scramp" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7022a140040f33cf863ab2657917ed05287a807b917950489b89b9f685d59bc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=42
    - versioningit >=1.1.1
  run:
    - python >=3.7
    - asn1crypto >=1.5.1
    - importlib-metadata >=1.0

test:
  imports:
    - scramp
  commands:
    - pip check
    - python -c 'import scramp; print(scramp.__version__)'
  requires:
    - pip

about:
  home: https://github.com/tlocke/scramp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pure-Python implementation of the SCRAM authentication protocol
  description: |
    A Python implementation of the SCRAM authentication protocol defined by
    RFC 5802 and RFC 7677.

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
